### ISSUE TITLE
Not working in IE and Edge

### ISSUE THREAD

**Issue by anwerso** [alnorris/file-dialog#1]
Change event fired immediately after `input.dispatchEvent(evt)` in IE, so to fix it we need to move `input.dispatchEvent(evt)` after attaching "change" listener in Promise.

**Comment by alnorris** [comment]
Thanks, @anwerso . Could you submit a PR request?, I don't have access to IE at the moment

**Comment by anwerso** [comment]
Not sure how you made minified version though.

**Comment by alnorris** [comment]
Thanks @anwerso , was just using a gulp minifier with babel
