### ISSUE TITLE
IE support

### ISSUE THREAD

**Issue by szkrd** [alnorris/file-dialog#4]
Hi! The README says "Support for all major browsers", could you please be more specific in the description at least with the minimum supported versions? I guess IE11 is supported, and maybe IE10, or am I wrong here? Thank you!

**Comment by alnorris** [comment]
@szkrd  It's been tested in Edge, not in IE11 or IE10. If you could do some testing and let me know that would be great. (file-dialog.min.js should be tested)

**Comment by szkrd** [comment]
I did a small test page only for myself back in the office, and it seemed to me that without adding the element to the body this will not work in IE (tested with IE10 mode in IE11). You can take a look at it [here](https://github.com/prepair/file-upload-example/blob/master/file-dialog.js) - it's quite silly I know, but did it in half an hour or so.

I also think that `initMouseEvent` has been deprecated. Not promising a PR though, sry :(

**Comment by szkrd** [comment]
This may be closed as far as [I can see](https://github.com/alnorris/file-dialog/commit/17603e8cb836ddefdb4bee75f83fc2d317f07dcf). Thank you!
